name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/ # Contains the food pictures youâ€™ll display throughout the app.
    - assets/magazine_pics/ # All the food magazine background images youâ€™ll display on card widgets.
    - assets/sample_data/ # The sample_data directory contains three JSON files:
    # sample_explore_recipes.json: A list of recipes to display on the home screen. Sometimes, users might want recommendations for what to cook today!
    # sample_friends_feed.json: This list contains samples of your friendsâ€™ posts, in case youâ€™re curious about what your friends are cooking up! ðŸ‘©â€ðŸ³
    # sample_recipes.json: A list of recipes including details about the duration and cooking difficulty of each.
    - assets/profile_pics/ # Contains raywenderlich.com team member pictures.
